### ISSUE TITLE
AttributeError: 'Space' object has no attribute '_initial_size'

### ISSUE THREAD

**Issue by liu9920ai** [Xiaokang2022/maliang#34]
### 🔖 Version

Latest development version

### 🔥 Platform

Windows 11

### ❓What Happened

我在3D练习中尝试使用three.Line函数时出现以下报错：
![image](https://github.com/user-attachments/assets/cebad125-2a58-4296-a90c-61c91daab4c1)
检查发现是因为'Space' 类没有'_initial_size'对象，于是我翻阅'Line'函数的具体文件，发现形参canvas的类型可以为’Space‘
![image](https://github.com/user-attachments/assets/62420440-5b6a-4f8e-8024-911ba281c112)
但是实例化集成‘Component’类时会在这个函数报错
<img width="1017" alt="屏幕截图 2024-08-27 233958" src="https://github.com/user-attachments/assets/dff6991a-4d6b-41ad-b3fd-52632ba53468">
不知道是我忽略了什么还是具体的类尚未修改或实现
python版本为3.12.5，具体包的版本如下：
![image](https://github.com/user-attachments/assets/65ed7941-3dad-4308-b67c-119298b742ea)

### 📑 Relevant Log Output

```shell
D:\VS2022\Python\tkintertools-demos\My_tkt3_ratice\Side_20_plot.py:2: DeprecationWarning: 'msilib' is deprecated and slated for removal in Python 3.13
  from msilib import add_stream
Traceback (most recent call last):
  File "C:\Users\liu\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liu\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "D:\VS2022\Python\tkintertools-demos\My_tkt3_ratice\Side_20_plot.py", line 29, in <module>
    plot_line_by_point_vector_and_distance(space,[1,0,0],[1,1,1],10)
  File "D:\VS2022\Python\tkintertools-demos\My_tkt3_ratice\Side_20_plot.py", line 17, in plot_line_by_point_vector_and_distance
    three.Line(space,p,[x2,y2,z2])
  File "D:\VS2022\Python\tkintertools-demos\tkt3env\Lib\site-packages\tkintertools\three\engine.py", line 469, in __init__
    self.update()
  File "D:\VS2022\Python\tkintertools-demos\tkt3env\Lib\site-packages\tkintertools\three\engine.py", line 474, in update
    for point in self._project(self.canvas._distance, self.canvas) for i, coord in enumerate(point)])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\VS2022\Python\tkintertools-demos\tkt3env\Lib\site-packages\tkintertools\three\engine.py", line 374, in _project
    lst = [(pos[0] + canvas._initial_size[0]/2, canvas._initial_size[1]/2 - pos[1])
                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Space' object has no attribute '_initial_size'
```

### ✉️ Contact Details

2404521002@qq.com

### ⚠️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caineblood** [comment]
that is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by Xiaokang2022** [comment]
@caineblood 

Thanks! I deleted that comment.

**Comment by Xiaokang2022** [comment]
@liu9920ai 

因为 3D 的代码本来是为 tkt 2 编写的，而 tkt 3 在框架上做了一定的更改，涉及到了画布缩放的机制，3D 部分的代码还没有完成对 tkt 3 的适配，所以有些不兼容。

不过目前还是有一些办法可以解决这个问题。你可以尝试以下代码：

```python
import tkintertools as tkt
import tkintertools.three as three

root = tkt.Tk()
space = three.Space(root, bg="black")
space.place(width=1280, height=720)

space.update()

three.Line(space, (0, 0, 0), (100, 0, 0), fill="red")
three.Line(space, (0, 0, 0), (0, 100, 0), fill="green")
three.Line(space, (0, 0, 0), (0, 0, 100), fill="yellow")

root.mainloop()
```

关键在于，在创建 `Space` 之后，必须在添加任何 3D 对象之前，添加 `space.update()`。由于内部实现细节不太容易解释，这里我只先告诉你可以这样解决这个问题，未来可能会优化 3D 模块，来省去这个代码。

如果仍然出现问题，请贴出报错部分的详细代码，方便我调试，谢谢。

**Comment by Xiaokang2022** [comment]
@liu9920ai 

可以参考演示仓库里有关 3D 的代码，或许对你有一定的帮助！

演示仓库：https://github.com/Xiaokang2022/tkintertools-demos

**Comment by liu9920ai** [comment]
> @liu9920ai
> 
> 因为 3D 的代码本来是为 tkt 2 编写的，而 tkt 3 在框架上做了一定的更改，涉及到了画布缩放的机制，3D 部分的代码还没有完成对 tkt 3 的适配，所以有些不兼容。
> 
> 不过目前还是有一些办法可以解决这个问题。你可以尝试以下代码：
> 
> ```python
> import tkintertools as tkt
> import tkintertools.three as three
> 
> root = tkt.Tk()
> space = three.Space(root, bg="black")
> space.place(width=1280, height=720)
> 
> space.update()
> 
> three.Line(space, (0, 0, 0), (100, 0, 0), fill="red")
> three.Line(space, (0, 0, 0), (0, 100, 0), fill="green")
> three.Line(space, (0, 0, 0), (0, 0, 100), fill="yellow")
> 
> root.mainloop()
> ```
> 
> 关键在于，在创建 `Space` 之后，必须在添加任何 3D 对象之前，添加 `space.update()`。由于内部实现细节不太容易解释，这里我只先告诉你可以这样解决这个问题，未来可能会优化 3D 模块，来省去这个代码。
> 
> 如果仍然出现问题，请贴出报错部分的详细代码，方便我调试，谢谢。

感谢回答，代码已成功运行
