### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by sum-is-light** [Xiaokang2022/maliang#6]
你好作者，我在继承tkintertools中的Tk时出现了递归报错，具体代码如下所示：
~~~python
import tkintertools as tkt


class TestExtendTk(tkt.Tk):
    """ 测试tkintertools的Tk继承 """
    def __init__(self, title: str | None = None, width: int | None = None, height: int | None = None, x: int | None = None, y: int | None = None, *, shutdown: None = None, alpha: float | None = None, toolwindow: bool | None = None, topmost: bool | None = None, transparentcolor: str | None = None, **kw) -> None:
        super().__init__(title, width, height, x, y, shutdown=shutdown, alpha=alpha, toolwindow=toolwindow, topmost=topmost, transparentcolor=transparentcolor, **kw)
        
        
if __name__ == "__main__":
    root = TestExtendTk('测试继承', 1280, 720)
    root.mainloop()
~~~
报错如下所示：
~~~shell
Traceback (most recent call last):
  File "c:\Users\86173\Desktop\Open-Source-Project\Label-Transformation-Tool\test\getattr-test.py", line 11, in <module>
    root = TestExtendTk('测试继承', 1280, 720)
  File "c:\Users\86173\Desktop\Open-Source-Project\Label-Transformation-Tool\test\getattr-test.py", line 7, in __init__
    super().__init__(title, width, height, x, y, shutdown=shutdown, alpha=alpha, toolwindow=toolwindow, topmost=topmost, transparentcolor=transparentcolor, **kw)
  File "D:\miniconda3\envs\test\lib\site-packages\tkintertools\main.py", line 75, in __init__
    self.geometry(f"{width}x{height}")
  File "D:\miniconda3\envs\test\lib\site-packages\tkintertools\main.py", line 128, in wm_geometry
    return tkinter.Tk.wm_geometry(self, geometry)
  File "D:\miniconda3\envs\test\lib\tkinter\__init__.py", line 2073, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
  File "D:\miniconda3\envs\test\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  File "D:\miniconda3\envs\test\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  File "D:\miniconda3\envs\test\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded
~~~
报错原因我在tkintertools中的Tk类的__init__实现中发现了，
~~~python
        if self.__class__ == Tk:  # NOTE: 方便后面的 Toplevel 类继承，只继承一部分功能
            tkinter.Tk.__init__(self, **kw)
~~~
这部分代码中的self.__class__==Tk的判定条件如果是继承情况结果就是False，导致继承类无法通过tkinter.Tk初始化数据。而在初始化函数的后期使用的wm_geometry中就会找不到属性，导致一直调用getattr，无限递归。

对于这个报错，我想问的是这个功能是不支持还是有其他考虑。主要是我在写程序的时候比较喜欢继承，需要扩展部分内容

**Comment by Xiaokang2022** [comment]
你使用的是 tkintertools 2 （2.6.21）对吧？实际上我已经不对 tkintertools 2 进行任何的支持了，如果可以，请使用 tkintertools 3（不过其仍处于 beta 版本）。

关于你提到的这个报错，这个 if 判断是刻意而为的，因为 tkt.Tk 的初始化方法存在部分内容（如 _zoom 方法的绑定）不应该被后续的类（如 tkt.Toplevel）所继承，但你实际上可以将其改为下面的代码，效果应该也是一样的（不保证正确）：

```python
if self.__class__ != Toplevel:  # NOTE: 方便后面的 Toplevel 类继承，只继承一部分功能
    tkinter.Tk.__init__(self, **kw)
```

由于我也很长时间没有碰过 tkintertools 2 的代码了，所以上面说的可能有误。

**Comment by Xiaokang2022** [comment]
不过我之前确实没有考虑过用户会直接继承这个类来增加一些功能的情况，此问题将会在 tkintertools 3 的后续版本中得到改进

**Comment by sum-is-light** [comment]
好的，感谢作者的帮助

**Comment by Xiaokang2022** [comment]
今日发布了 `3.0.0.beta2` 版本，此 bug 已在该版本中修复
